spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  sql:
    init:
      mode: always
security:
  jwt:
    secret-key: customshoppingmallservice
    access-token-expiration-time: 1800000    # 30 minutes in milliseconds
    refresh-token-expiration-time: 86400000  # 1 day in milliseconds
superAdmin:
  id: "superadmin"
  pw: "superadmin_password"
cors:
  allowed:
    origins: http://localhost:3000
file:
  storage:
    type: "local"
  local:
    upload-dir: "/customshoppingmallservice/test-local/image"